// `npm run db-local` — brings up the local Postgres, applies every migration
// including the unmerged ones, and writes .env.localdb so `npm run dev:local`
// points the app at it.
//
// Nothing here can reach production: every CLI call below is --local, and the
// one command that writes to production, `npm run db-push`, is untouched and
// still manual. See plan 9.

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const ENV_FILE = '.env.localdb';

/** Runs a CLI command, showing its output; throws on a non-zero exit. */
function run(args: string[]): void {
	execFileSync('supabase', args, { cwd: ROOT, stdio: 'inherit' });
}

/** Runs a CLI command and returns its stdout instead of printing it. */
function capture(args: string[]): string {
	return execFileSync('supabase', args, { cwd: ROOT, encoding: 'utf8' });
}

// `start` on an already-running stack is an error, not a no-op, and "already
// running" is the normal case here — so its failure is only fatal if the stack
// turns out not to be up afterwards.
try {
	run(['start']);
} catch {
	console.log('(stack already running)');
}

// Applies migrations written since the stack was last started or reset, which
// is the whole point on a feature branch: a new event type's row lands here
// without production seeing it.
try {
	run(['migration', 'up', '--local']);
} catch {
	// A Node stack trace says nothing useful here, and the common cause has a
	// one-line fix: deleting a migration file that was already applied leaves
	// the history table ahead of the directory, which a reset rebuilds.
	console.error(`
✖ applying migrations to the local database failed — the CLI's error is above.

  If it mentions migration versions not found locally, a migration that was
  applied here has since been deleted or renamed. Rebuild from the files:

    npm run db-local:reset
`);
	process.exit(1);
}

const status = capture(['status', '-o', 'env']);
const values = new Map<string, string>();
for (const line of status.split('\n')) {
	const match = /^([A-Z_]+)="(.*)"$/.exec(line.trim());
	if (match) {
		values.set(match[1], match[2]);
	}
}

const apiUrl = values.get('API_URL');
const publishableKey = values.get('PUBLISHABLE_KEY');
if (!apiUrl || !publishableKey) {
	console.error('✖ could not read API_URL and PUBLISHABLE_KEY from `supabase status`.');
	process.exit(1);
}

// A mode env file, read only by `vite dev --mode localdb`. Vite loads .env
// first and lets the mode file win, so the production .env is never touched and
// plain `npm run dev` still points at production.
//
// These are the CLI's fixed local development values — the same on every
// machine — not secrets. The file is gitignored regardless, with the rest of
// .env.*.
writeFileSync(
	join(ROOT, ENV_FILE),
	`# Generated by npm run db-local. Not committed; regenerated on every run.\n` +
		`PUBLIC_SUPABASE_URL=${apiUrl}\n` +
		`PUBLIC_SUPABASE_PUBLISHABLE_KEY=${publishableKey}\n`
);

console.log(`
wrote ${ENV_FILE} — ${apiUrl}

  npm run dev:local     the app, against this database
  ${values.get('STUDIO_URL') ?? 'http://127.0.0.1:54323'}   Studio, to look at the tables

Log in as dev@local / localdev. The history is empty until you log something,
or until you copy production's:

  npm run db-pull       snapshot production's data into this database (read-only)
  npm run db-local:stop stop the stack
`);
