// The pure half of `npm run db-pull`: a pg_dump of production's data in, a seed
// file the local database can actually load out. No filesystem, no network —
// those live in db-pull.ts — so the wrapping is testable
// (tests/db-pull.test.ts) without touching either database.

/**
 * Wraps a `--data-only` dump of production's public schema so that
 * `supabase db reset` can load it after seed.sql.
 *
 * Three things stand between the raw dump and a database it will load into,
 * and each is handled here rather than by editing the dump:
 *
 *   1. Production's user ids do not exist locally, and both
 *      `household_members.user_id` and `events.created_by` reference
 *      `auth.users`. Rather than copy password hashes onto disk, the rows are
 *      re-pointed at the seeded local login *after* loading — which needs the
 *      foreign keys quiet during it, hence `session_replication_role`.
 *   2. seed.sql's own household would otherwise sit beside production's,
 *      leaving the app with two dogs. It is truncated first.
 *   3. `household_members` is rebuilt rather than updated: two members of one
 *      household would both collapse onto the single local user and collide on
 *      the primary key.
 *
 * `login` is matched by email rather than by id so that no uuid is duplicated
 * between this file and seed.sql.
 */
export function buildSnapshot(dump: string, login: string): string {
	const user = `(select id from auth.users where email = '${login}')`;

	return `-- Generated by npm run db-pull. Not committed: this is production's data.
-- Loaded by \`supabase db reset\` after seed.sql, which creates the login this
-- file attaches everything to.

-- Foreign keys off for the load: the dump references production's user ids,
-- which are rewritten to the local login at the bottom of this file.
set session_replication_role = replica;

truncate events, dogs, household_members, households cascade;

${dump.trim()}

delete from household_members;
insert into household_members (household_id, user_id)
select h.id, u.id from households h, auth.users u where u.email = '${login}';

update events set created_by = ${user};

set session_replication_role = origin;
`;
}
